### ISSUE TITLE
CocoaPods?

### ISSUE THREAD

**Issue by andreacremaschi** [Syphon/Syphon-Framework#1]
Hey I saw you moved the project on GitHub, welcome! :)
Now it would be easier to integrate Syphon in [CocoaPods](http://www.cocoapods.org) to make it easier to add it in a new project. Do you know it? I myself wished a Syphon pod to exist. 
If you wish I can write a specification for the project.
Ciao
a.

**Comment by fish2000** [comment]
+1 for CocoaPods, for what it’s worth…
In the interim, anyone wanting to do a quick and dirty build-and-install of the framework can avail themselves of [this Homebrew formula I have in my tap](https://github.com/fish2000/homebrew-praxa/blob/master/syphon.rb) – as straightforward as:

    $ brew tap fish2000/praxa
    $ brew install syphon

Share & Enjoy!
