### ISSUE TITLE
GL 3 + 4 support

### ISSUE THREAD

**Issue by casey** [Syphon/Syphon-Framework#13]
I'm using GLFW on Mavericks with an OpenGL core 4.1 context with forward compatibility turned on.

After my first call to bindToDrawFrameOfSize:, glGetError() returns GL_INVALID_OPERATION. Subsequent calls produce no error.

Everything still works as expected, however, and I can see my published frames in the Simple Client.

My guess is that something in setupIOSurfaceForSize: is causing problems, perhaps glPushAttrib, which is deprecated.

I would prefer to use publishFrameTexture:, but it doesn't work at all, I suspect because it makes much more extensive use of deprecated functions. Is there a branch lurking out there that fixes this, or a suggested workaround?

**Comment by rsodre** [comment]
Hi guys! Any news on this? I finally took courage to delve into GL3.
Looks like GL_TEXTURE_RECTANGLE_ARB has limited support on GL3, and GL_TEXTURE_2D accepts NPOT textures. Do you see Syphon going for GL_TEXTURE_2D, at least client-wise?

**Comment by vade** [comment]
IOSurface only supports texture rectangle last I checked so internally rect support need - :) 

://:; mbl.dev.

**Comment by pizthewiz** [comment]
@eromanc's [fork](https://github.com/eromanc/Syphon-Framework) is said to support both legacy and core profile too.

**Comment by vade** [comment]
* [ ] - finish the state capture and restore code path
* [ ] - performance analysis on the shared context
* [ ] - performance analysis on state capture vs no capture

**Comment by bangnoise** [comment]
work in progress in core-profile branch

**Comment by bangnoise** [comment]
I cannot measure a performance penalty using a shared context and switching to it. I very much favour this as an approach as we needn't interfere with caller state. I would propose that all our GL work is done in the shared context with the exception of ````-bindToDrawFrameOfSize:```` and ````-unbindAndPublish```` - these would affect the caller's context, but only the FBO binding (which would be bound to the default 0 framebuffer on unbind). All preparatory work to build our FBO and attachments would be done in our private shared context. In the case of ````-publishFrameTexture:...```` we would switch to our private context prior to the bind/unbind, so no changes would be made in the caller's context.

Unless @vade or anyone has objections I will go with this and perhaps feedback from testers will affect the final decision on this.

**Comment by bangnoise** [comment]
Closing this as it's merged to master - [alpha release](https://github.com/Syphon/Syphon-Framework/releases) is available, will move to final release soon unless any issues pop up.
