### ISSUE TITLE
GPU crash with IntelHD/10.10

### ISSUE THREAD

**Issue by lov** [Syphon/Syphon-Framework#17]
Hello Guys,

ran into a GPU restarting problem which only occurs on 10.10 with Intel HD GPUs. Really hard to reproduce, and I am not sure this is related to Syphon and not a driver problem.

In a nutshell, I have a window with an NSOpenGLContext, and while resizing the window sometimes the GPU restarts in the background, sometimes crash on the publishFrameTexture... method. I have locks around the GL calls, so I believe this is not related to that, and surprisingly the issue stops when I don't send frames via Syphon.

I have a relatively minimal example project as well as a little screen record about the problem - maybe I just make something stupid there?

https://dl.dropboxusercontent.com/u/2533/gpucrash.zip

**Comment by vade** [comment]
Hrm. Some quick thoughts without having run the code myself, just a quick look.

Reshape isn't overrided, and you don't lock the context in there etc as you do everywhere else.

Is it sufficient to simply override update, and not call super method for update? The header states the implementation only calls update on the context, but it might be safer to call [super update] there.

Any chance we can have some logs? I didn't see them in the zip :) Thanks!

**Comment by lov** [comment]
> Reshape isn't overrided, and you don't lock the context in there etc as you do everywhere else.

Yep, that is not overrided because the default implementation of that method does nothing: https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSOpenGLView_Class/#//apple_ref/occ/instm/NSOpenGLView/reshape

> Is it sufficient to simply override update, and not call super method for update?

Calling supers update method probably safer that - I just changed that to update the context directly too see if that makes any difference and forgot the change back.

BTW, I forgot to mention, but as I found the trouble-maker is the flushing after clear during update. If I just comment calling of clearScreen then there are no problems.

> Any chance we can have some logs?

Of course, here you go: https://dl.dropboxusercontent.com/u/2533/logs.zip

**Comment by vade** [comment]
Ah right I forgot reshape is a no-op - thanks for reminding me :) 

Interesting thats the issue. Weird. Thanks for the logs!

**Comment by lov** [comment]
You're welcome, and thanks for looking into this :)

Anyway, I think this is not a show-breaker at all, since it is hard to reproduce, but annoying, and smells like a drive bug in my opinion, in case I don't do anything stupid there :)

**Comment by vade** [comment]
Hm. Just a random question - if you run GL profiler and break on GL Error - do you get any errors thrown ? If not - i'd open up a case with Apple perhaps?

Sorry I haven't run it yet, I'm in the midst of some work stuff. Let us know!

**Comment by lov** [comment]
Sure, I did tests with GL profiler but no GL errors found - I think I did everything what I could do before posted this.

Talked with Tom last night about this by the way. The only thing which I found with GL profiler it crashes the app when GPU restarts - but I think that happened because GL profiler cannot handle GPU restart while profiling (btw, I'm using a bit older GL profiler, from the Mavericks era I guess, since that is the latest one which is actually working... ).

**Comment by lov** [comment]
Well, now I found a way to reproduce the exact same behaviour by putting a Core Image filter into the chain and render it to an FBO, so this is definitely not Syphon related at all. 

I'll let Apple know about the issue, thanks for looking into this anyway, and sorry for wasting your time! :)

**Comment by vade** [comment]
Oh man - lots of Core Image issues in 10.10. I wonder if this has to do with glFlushRenderAPPLE which I think CoreImage uses as well. I didn't see that call in your code. Just a random random thought.

Thanks for following up!

**Comment by vade** [comment]
Yea thats why I brought up that call. You could maybe, if you wanted, make a custom syphon framework by switching that call to glFlush() rather than glFlushRenderApple() and see if the issue goes away. That would be *really* interesting. Again, just speculating, Im over the shoulder debugging here, haha.

**Comment by lov** [comment]
Yep, good call! I'll do a test later for sure when I'll have some free time - already spent 2 days on this beast, and things should go forward.
But anyway, to avoid flushing on the main thread fixes the issue and while it is an ugly workaround, but seems to working. And since there is a good chance people will use CI stuff anyway, I need a bit more broad solution.

**Comment by lov** [comment]
DTS confirmed this seems to be a driver level issue, filed a bug report as #19712426
