### ISSUE TITLE
When a Syphon client connects to a still server, should receive the last published frame

### ISSUE THREAD

**Issue by rsodre** [Syphon/Syphon-Framework#28]
If a server is alive but not publishing frames and a client connects to it, the client will remain black until the server starts publishing again.
The client should receive the last published frame upon connection.

**Comment by bangnoise** [comment]
are you using a newFrameHandler in the client?

**Comment by rsodre** [comment]
It's happening with the Unity 3D client, it might not be using it, I'll check.
Simple Client works, it is reading the last frame.
