### ISSUE TITLE
Can't compile Syphon-Framework in XCode 7

### ISSUE THREAD

**Issue by eighteight** [Syphon/Syphon-Framework#30]
Out of the box checkout produces the following error

```
clang: error: garbage collection is no longer supported
```

**Comment by bangnoise** [comment]
Mysterious - works for me, and GC-support was removed a while ago (e0015732f0b7758889cb8c1a6027d96e6ed9bc40). Can you make sure you really are at the latest commit?

**Comment by eighteight** [comment]
It turns out I was using "float" branch. Thanks for updating master to XCode 7 -- it works now.
