### ISSUE TITLE
Syphon changes the texturing while running in the GPUImage host

### ISSUE THREAD

**Issue by eighteight** [Syphon/Syphon-Framework#31]
I am getting the following glitch in a syphon client from a syphon server embedded into GPUImage application, which seems to be due incorrect texture indexing in the syphon server.

![Image of Triangle glitch in syphon client](http://i.stack.imgur.com/2SkwL.jpg)

In the GPUImage host I am using GL_TRIANGLE_STRIP to render the textures, and that works fine.

**Comment by bangnoise** [comment]
cf http://v002.info/forums/topic/triangular-glitch-as-displayed-in-simple-client/

(cross-posting is kind of annoying)

    [myServer publishFrameTexture:GL_TEXTURE0 textureTarget:GL_TEXTURE_RECTANGLE_EXT imageRegion:NSMakeRect(0, 0, size.width, size.height) textureDimensions:size flipped:YES];

GL_TEXTURE0?

**Comment by eighteight** [comment]
>GL_TEXTURE0? 
It's current texture id.

**Comment by eighteight** [comment]
I just recompiled Syphon Framework, changing GL_TRIANGLE_FAN to GL_TRIANGLE_STRIP, and that got rid of the glitch.

Still puzzled why that had an effect.

Also, not sure why GL_TRIANGLE_FAN was in the first place.

**Comment by vade** [comment]
PublishFrameTexture takes a GLUint returned from glGenTextures so - a texture ID. GL_TEXTURE0 is a Texture Unit assignment, conceptually different :)

**Comment by bangnoise** [comment]
closing this, no bug

**Comment by eighteight** [comment]
>PublishFrameTexture takes a GLUint returned from glGenTextures so - a texture ID. GL_TEXTURE0 is a Texture Unit assignment, conceptually different :)

It was a copy/paste from a code that was being worked on. However actual GLUint value is correct.

Care to comment on GL_TRIANGLE_FAN effect?

Thanks.

**Comment by vade** [comment]
Well - you could have a bound PBO, a bound index buffer, or all sorts of other issues within GPU that is leaking OpenGL state and corrupting GL within Syphon. Suffice it to say there are hundreds of shipping apps that have nary had that issue within the framework and that is the most used method of Syphon. 

I suspect something else is going on.

**Comment by vade** [comment]
Not to be dismissive by any means - are you using other branches ? Are you checking for GL errors via GL profiler or in your code? Lots can go wrong in middle ware. However, basic rendering has not ever been a problem within Syphon itself. OpenGL State leaks can be an issue, or incorrect state assumptions by host apps.

**Comment by eighteight** [comment]
The Syphon server has been embedded into a host, which had been in use before for a year without any problems. I _am_ using GL errors checks.

Can you recommend how to debug the issue with the Syphon server embedding I am having?

Thanks.

**Comment by bangnoise** [comment]
If you can share the simplest possible code which reproduces the problem, we can take a look.
