### ISSUE TITLE
Not working on macOS 10.12.4

### ISSUE THREAD

**Issue by surmvoise** [Syphon/Syphon-Framework#37]
I just updated to macOS 10.12.4 and noticed that Syphon Recorder is not working anymore. I can launch it but cannot select an input (buttons are greyed out). Is this a common issue?

<img width="632" alt="bildschirmfoto 2017-04-06 um 15 06 45" src="https://cloud.githubusercontent.com/assets/6092775/24755477/aaf5351a-1ada-11e7-9302-74bc1fda9a5a.png">

**Comment by bangnoise** [comment]
Syphon Recorder issues at the [v002 forum](http://v002.info/forums/forum/syphon/syphon-implementations-user/) please. When you post, include information on the app you're sending from, and check your copy of Recorder is up to date.

**Comment by surmvoise** [comment]
Nevermind, just realized it's working perfectly fine. I forgot to send the image via Syphon. Sorry.
