### ISSUE TITLE
SyphonServerDirectory not listing servers and not sending notifications

### ISSUE THREAD

**Issue by hipersayanX** [Syphon/Syphon-Framework#39]
Hi, I've downloaded the the [client and server examples](https://github.com/Syphon/Simple/releases/tag/version-3) and linked my project with Syphon.framework included in the client, and then opened the example server, and tried listing the available servers with:

    NSArray *available = [[SyphonServerDirectory sharedDirectory] servers]

as suggested by the documentation, available.count is returning 0, and when closing and reopening the server many times, the SyphonServer*Notifications are never triggered. I'm linking with Foundation.framework too, and the example client and server are communicating between them well. I'm using OS X 10.12.
Maybe I'm need to link to another framework? or maybe I need to initialize something else?

**Comment by vade** [comment]
Is your app sandboxed? Syphon uses distributed NSNotifications for announce / retirement and is one of the mechanisms we use. 

We currently don't support sandboxing for Mac App Store due to sandboxing restrictions on notifications and on IOsurface global lookup.

**Comment by vade** [comment]
Also your app needs an NSRunloop installed typically by way on NSApplication to service notifications. If by chance you don't have an NSRunloop that might be your issue

**Comment by hipersayanX** [comment]
I'm pretty sure my app is not sandboxed, about NSRunloop not sure, I'm using Qt and not sure if Qt is using NSRunloop under the hood. [Here](https://github.com/hipersayanX/SyphonQtTest) is the code I'm using to test it.

**Comment by vade** [comment]
You need to install an NSRunloop I believe if you are using QT.

**Comment by hipersayanX** [comment]
Ok, solved creating a QTimer (or the equivalent for Foundation framework) and then running this inside:

    [[NSRunLoop currentRunLoop]
     runMode: NSDefaultRunLoopMode
     runBeforeDate: [NSDate dateWithTimeIntervalSinceNow: 1]];

or

    [[NSRunLoop currentRunLoop]
     runUntilDate: [NSDate dateWithTimeIntervalSinceNow: 1]];

**Comment by vade** [comment]
Nice glad that worked out!

**Comment by hipersayanX** [comment]
One more update, changing from QCoreApplication to QGuiApplication, seems that QGuiApplication already implements NSRunLoop internally, so the timer code is not required in that case.
