### ISSUE TITLE
Download link on website is down

### ISSUE THREAD

**Issue by dorfman2** [Syphon/Syphon-Framework#40]
When I attempt to download from http://syphon.v002.info/, I get this 404 error;

> 404. That’s an error.
> 
> The requested URL /files/Syphon%20SDK%20Public%20Beta%202.zip was not found on this server. That’s all we know.

**Comment by bangnoise** [comment]
I've just put up a new [release](https://github.com/Syphon/Syphon-Framework/releases) and linked to it from the Syphon website.
