### ISSUE TITLE
Syphon Client as input into GPUImage framework

### ISSUE THREAD

**Issue by eighteight** [Syphon/Syphon-Framework#41]
Has anybody embedded Syphon Client into GPUImage framework?

Any pointers would be appreciated.

**Comment by vade** [comment]
Does GPUImage support Desktop these days? Last I looked was many years ago and it was early iOS only.

A better question is, what is it you are looking to do, and what is your image processing pipeline.

**Comment by eighteight** [comment]
GPUImage supports Desktop, I have GPUImage App feeding a Syphon Server since 2015, used in many applications. Now I need to also feed external Syphon input into my GPUImage App. So my processing pipeline is GPUImage-based.

**Comment by vade** [comment]
Ok, so you cant use a SyphonImage vended from a client as a texture in GPU Image?

Does GPU Image support just, actual pure GL Texture references?

**Comment by eighteight** [comment]
I would not say I can't, I just am not sure where to drop it into a pipeline. GPUImage supports raw opengl, look at [this line](https://github.com/BradLarson/GPUImage/blob/master/framework/Source/GPUImageMovie.m#L660), for example. It seems I could put there a SyphonImage.textureName

**Comment by vade** [comment]
Yea, honestly, reminding me of the sources, its not really designed clearly IMO. 

I think you want to subclass GPUImageOutput and implement a custom GPU Image source (the raw data "input"  is a subclass of  GPUImageOutput rather than implementing an GPUProcessing protocol :X )

Make a custom GPUImageOutput - skip all the CVPixelBuffer bullshit and just shit out textures. I don't think you can vend a CVOpenGLTextureRed from anything other than a CVOpenGLTextureCache (they are opaque and I don't think you can malloc, new, create them with a Gluint texture ID) so you'll have to do some hacking about, but it should be doable.

YMMV.

**Comment by eighteight** [comment]
That's what I am basically doing: my SyphonClient wrapper implements GPUImageOutput, and gets the SyphonImages all right, however [GPUImageOutput](https://github.com/BradLarson/GPUImage/blob/master/framework/Source/GPUImageOutput.h) interface is not clear which method I should override to drop the SyphonImage frames into outputFramebuffer as they come. I guess I'll have to try them one at a time.

**Comment by vade** [comment]
Cool, good luck, sounds like this is just an integration issue then - mind if I close?

**Comment by eighteight** [comment]
Thanks. Before you close, do you know of any similar examples of integration?

**Comment by vade** [comment]
Well, every app that uses Syphon has had to implement 'integration' into their pipeline for OpenGL. I'd peruse Github for some of the SyphonClient API calls and see if you can find what you need perhaps?

**Comment by vade** [comment]
BTW - Sorry if that came off as dismissive, please feel free to post / ask any specific questions in the future !

**Comment by eighteight** [comment]
Had a second go at this, and it kinda works. A problem I was facing had to do with the syphon's texture target being GL_TEXTURE_RECTANGLE_ARB, while GPUImage works with GL_TEXTURE_2D. The conversion in my case happens in the shader while copying syphon's texture into the GPUImage outputFrameBuffer attachment.



[GPUImageSyphonClient.zip](https://github.com/Syphon/Syphon-Framework/files/2476811/GPUImageSyphonClient.zip)
