### ISSUE TITLE
can the client connect to remote server?

### ISSUE THREAD

**Issue by assegid** [Syphon/Syphon-Framework#42]
Hi, may be I am trying to do something this tool is not designed to do. Can the syphon client connect to a remote server using IP and port, or does it only work on local port? I see the server displays its IP and the port it is using, but I cannot find a way to enter the sever address using the syphon client. I am using the TCPsyphonserver/client apps.

**Comment by vade** [comment]
Hi.

TCP Syphon is not a project /product that the core Syphon dev's develop - it does leverage the Syphon framework, and in theory it can work how you want it to, but its designed for local (LAN) transport of video, not streaming. 

Syphon framework itself is designed to share, incredibly efficiently, video in one programming running on one host (local host) to another program running on the same local host. Syphon Framework itself has no (current?) networking capability.

**Comment by vade** [comment]
I'd suggest you hit up the TCPSyphon devs ! Also, Streaming / remote / over network can be really tricky. Try out OBS or Wirecast both which have Syphon support, so you can stream content from one local Syphon Server into a local WireCast or OBS program, and then send that out to the net.

**Comment by assegid** [comment]
Thank you for the quick response. I wanted to try TCPsyphon because it seemed like that is the preferred tool from the main page on your website. Perhaps because the applications in the demo were in the same room. My need is for a high performance streaming environment that is least affected by network bandwidth. BTW, I did manage to get the streaming accomplished between remote machines using UDPsyphon, I am using it with Max7/jitter. What is your recommendation for the best performance live streaming development platform that possibly includes audio with a good open source SDK?
