### ISSUE TITLE
CGLContext leak in SyphonServer with SYPHON_CORE_SHARE

### ISSUE THREAD

**Issue by TroikaTronix** [Syphon/Syphon-Framework#48]
If SYPHON_CORE_SHARE is TRUE then the call "_shareContext = CGLRetainContext(context);" in **initWithServerDescription:context:options:newFrameHandler** is not balanced by a CGLReleaseContext call, introducing a potential context leak.

Here's the code from SyphonServer.m

```
#ifdef SYPHON_CORE_SHARE
			_shareContext = CGLRetainContext(context);
			if (SyphonOpenGLContextIsLegacy(context))
			{
				_context = CGLRetainContext(context);
			}
			else
			{
				_context = SyphonOpenGLCreateSharedContext(context);
			}
#else
			_context = CGLRetainContext(context);
#endif
```
balanced by this in the **stop** method

```
    if (_context)
    {
        CGLReleaseContext(_context);
        _context = NULL;
    }

```
I fixed this in my version as follows

```
    if (_shareContext)
    {
        CGLReleaseContext(_shareContext);
        _shareContext = NULL;
    }
    if (_context)
    {
        CGLReleaseContext(_context);
        _context = NULL;
    }

```

**Comment by bangnoise** [comment]
Thanks and oops! For any confused observer this issue was in SyphonClient, not SyphonServer.
