### ISSUE TITLE
Script to preprocess exports file requires update

### ISSUE THREAD

**Issue by bangnoise** [Syphon/Syphon-Framework#52]
We need to properly build individual -D arguments from GCC_PREPROCESSOR_DEFINITIONS, the current version no longer works

**Comment by vade** [comment]
This a breaking change in LLVM / Xcode 11 ?

**Comment by bangnoise** [comment]
Assume so, couldn’t say for sure when it stopped working. It only affects builds with a custom class-name prefix, not regular builds. I‘m not sure my original form for providing the definitions was ever correct.
