### ISSUE TITLE
What is expected behaviour of syphon server "HasClients"

### ISSUE THREAD

**Issue by richardwilliamson** [Syphon/Syphon-Framework#62]
Hello

I was planning to used "HasClients" on a syphon server as a method to determine whether or not to render anything to the server, however this seems to return false even when client(s) have attempted to connect to the server (tested with qlab and simple client) - the clients can see the server is there and select it but the property on the server doesn't become true.

Do I need to send a frame every so often to allow the clients to connect or am I totally mis-understanding the purpose of the property?

Thanks!

Richard

**Comment by bangnoise** [comment]
The `hasClients` property works for me. Can you provide a code snippet that's not working as you expect?

I notice you're capitalising it `HasClients` - are you using some other framework or wrapper, eg Processing?

**Comment by richardwilliamson** [comment]
Thanks Tom 

Just as I go to send you some code I realise I am an idiot.. I was testing:

if ([_syServer hasClients])
        return;

Which obviously did the opposite to what I was wanting to do!

Sorry and thanks for your help!

Richard

---
Richard Williamson
www.richard-williamson.com
richard@theatre.support
07957 457 362

**Comment by bangnoise** [comment]
Glad it's working - we are all idiots sometimes
