### ISSUE TITLE
Syphon to virtual webcam.

### ISSUE THREAD

**Issue by illu667** [Syphon/Syphon-Framework#63]
I guess there isn‘t an official solution yet, isn‘t it? I know I can use CamTwist and Syphon Virtual Webcam by TroikaTronix. But they use pretty much resources…
So I wanna suggest / ask for something like that :)

Keep up the great work!

**Comment by playaspec** [comment]
If you're looking to ultimately use that virtual camera for streaming, maybe Syphon to NDI would be useful? I've never used this personally, so can't vouch for it's utility.

https://docs.vidvox.net/freebies_ndi_syphon.html

**Comment by bangnoise** [comment]
This is beyond the scope of the framework - we'd encourage you to use a third-party solution which integrates Syphon - and give them feedback if they're not working for your purposes.
