### ISSUE TITLE
Apple Silicon Release

### ISSUE THREAD

**Issue by rsodre** [Syphon/Syphon-Framework#64]
I know the framework is already compatible with Apple Silicon but would be good to have a published release built for it.

**Comment by benkuper** [comment]
Is there actually a release somewhere now ? or has this just been closed ?
Tried the website mentionned in the readme as well but it seems dead.

**Comment by bangnoise** [comment]
We're reviewing how we do releases - currently you'll have to build from source. Hopefully not a problem.

The website's at http://syphon.github.io at the moment - I'll update the README until we get it fixed.

**Comment by benkuper** [comment]
Not really a problem, would still be a lot easier to have a unified x64+arm64 framework ready to use :) github releases are quite good for that i'd say ?

**Comment by bangnoise** [comment]
Yes, we have previously offered Github releases, and may do so in the future. Right now we are focussing our limited time on development.

Open Syphon.xcodeproj > Product > Archive > Distribute Content > Built Products > Export gives you a universal framework ready to use.

**Comment by 2xAA** [comment]
@bangnoise @vade Any update on building a universal framework?

Would be ideal to download the framework rather than building it.

We're trying to complete the final step in https://github.com/benoitlahoz/node-syphon which is making this a consumable package, so either we host a universal build somewhere ourselves or we instruct users of the module to build syphon themselves.

**Comment by vade** [comment]
FWIW, i'd be open to hosting builds of the framework, but ideally, if you are:

* offering a development repo, it should be buildable there without needing 3rd party manual installs (ie - use a submodule and provide build instructions / tooling)
* offering a downloadable release, it should be appropriately packaged into the release / installer without needing a user to go and get something and put it somewhere as a install step

**Comment by benoitlahoz** [comment]
New version of [`node-syphon`](https://github.com/benoitlahoz/node-syphon) is now hosting an universal build of Syphon framework in its `Releases` section (is it ok?).  The framework, cloned directly from your repo, [is built with no modifications](https://github.com/benoitlahoz/node-syphon/blob/main/scripts/build-syphon.sh). 

Library contributors can install it (or eventually rebuild it, which is not necessary at this point), **but installing it as a dependency is transparent for final user** who needs to include it in their own application.

The package published on `npm` no longer includes the framework: it is automatically downloaded and unzipped at the right place in a [`postinstall` step](https://github.com/benoitlahoz/node-syphon/blob/main/postinstall.sh). 

It would be great to have this `postinstall` download an *official* release from your own repository. 

NB: after some headaches the framework is now linked correctly and our addon is built for both Intel and Silicon architectures. We're working on a specific `Electron` library built on top of this one.
