### ISSUE TITLE
Alpha channel unchecks itself?

### ISSUE THREAD

**Issue by thegergs** [Syphon/Syphon-Framework#68]
Running Syphon on 2018 iMac, I've never had a problem with it sending the alpha channel. In the past three weeks the box randomly unchecks itself.  What is the solution for this issue?  Thanks!

**Comment by bangnoise** [comment]
This is the repo for the Syphon framework used by developers in their applications. What application are you using?

**Comment by thegergs** [comment]
We are using presentation software called ProPresenter to show lower third
lyrics for our songs and teaching notes at our church. iMac 2018, fully
updated OS.  This has only been happening for a month now, it was never an
issue before. Thanks for any ideas you may have.

**Comment by bangnoise** [comment]
Please pursue this with ProPresenter - this is a problem with ProPresenter, not Syphon.

**Comment by thegergs** [comment]
Thank you. I thought so, but their support says it's not. I do appreciate
your help.
