### ISSUE TITLE
Documentation or simple send&receive example in swift ?

### ISSUE THREAD

**Issue by eetteri** [Syphon/Syphon-Framework#73]
I'm making simple middleware app that needs to push frames to syphon pipe. I'd like to do this in swift with bridging header. Are there any working examples or documentation how to set it up?

I've found this project https://github.com/pixlwave/Syphon-Swift-Example but at least I'm getting bunch of compile time errors with the latest Syphon.framework I tried it with.

**Comment by vade** [comment]
Documentation is here:

http://syphon.v002.info/FrameworkDocumentation/

Example implementations are all here:

https://github.com/Syphon

**Comment by vade** [comment]
How about you share what your errors are?

**Comment by eetteri** [comment]
Sorry, of course. I've got the latest Syphon Framework, I've build it and added it to the simple swift example project mentioned above. 

These are the errors

Syphon Swift Example/ViewController.swift:29:27: Cannot find 'glGenTextures' in scope
Syphon Swift Example/ViewController.swift:58:21: Cannot find 'glBindTexture' in scope
Syphon Swift Example/ViewController.swift:58:42: Cannot find 'GL_TEXTURE_RECTANGLE_EXT' in scope
Syphon Swift Example/ViewController.swift:59:76: Cannot find 'GL_TEXTURE_RECTANGLE_EXT' in scope
Syphon Swift Example/ViewController.swift:59:110: Cannot find 'GL_RGBA' in scope
Syphon Swift Example/ViewController.swift:59:170: Cannot find 'GL_BGRA' in scope
Syphon Swift Example/ViewController.swift:59:187: Cannot find 'GL_UNSIGNED_INT_8_8_8_8_REV' in scope
Syphon Swift Example/ViewController.swift:64:74: Cannot find 'GL_TEXTURE_RECTANGLE_EXT' in scope

To me it seems that those errors are not related to the syphon framework rather than some openGL stuff hence I was looking if there exists some other example how to set things up properly.

**Comment by vade** [comment]
You need to include OpenGL.framework which should (?) have bindings for Swift. But since OpenGL is deprecated you need to use a Metal renderer, which Syphon has (see our metal branch)

Alternatively see https://github.com/Syphon/Simple for a simple setup in Objective-C

**Comment by eetteri** [comment]
Thanks. I would like to stay in swift land as much as possible. I'll try to take the older swift example and convert that to use metal instead of openGL. 

For Syphon part, I just need to grab the metal branch and build the framework from that and it should be ok?

**Comment by vade** [comment]
Exactly!

**Comment by eetteri** [comment]
Started to work on creating simple server demo on swift+metal. @vade mentioned that there should be metal branch but I can't seem to find it. Is it on some other repo than this?

**Comment by bangnoise** [comment]
https://github.com/anome/Syphon-Framework/tree/subclassing-metal
