### ISSUE TITLE
Crashes in Clients when Servers exit without using stop

### ISSUE THREAD

**Issue by smilingthax** [Syphon/Syphon-Framework#74]
(I'm using a custom compile of the current git master, on Apple Silicon.)

To reproduce:
1) start SimpleClient
2) start SimpleServer (e.g. from the command line)
3) kill SimpleServer (e.g. `Ctrl-C`)
4) start SimpleServer again (or any other Syphon Server)
5) after a few seconds SimpleClient crashes.

Case 1: (not necessarily using the above steps)
Stack trace:
```
0   libobjc.A.dylib                       0x1992d7258 objc_class::isInitialized() + 0
1   libobjc.A.dylib                       0x1992c3d28 object_getMethodImplementation + 104
2   CoreFoundation                        0x1994ac9c4 _NSIsNSArray + 40
3   CoreFoundation                        0x199527b60 -[NSArray isEqual:] + 60
...
13  Foundation                            0x19a53b190 NSKeyValueDidChangeWithPerThreadPendingNotifications + 160
14  Syphon                                0x100b7e334 -[SyphonServerDirectory handleServerAnnounce:] + 432
```

Case 2: (the one usually(?) triggered by the above reproduction steps)
Log output just before Crash: 
```
SimpleClient[21668:1598266] SYPHON DEBUG: SyphonServerDirectory: Removing servers which didn't respond to an announce request.
```
Stack trace:
```
...
13  Foundation                            0x19a53b190 NSKeyValueDidChangeWithPerThreadPendingNotifications + 160
14  Syphon                                0x10020d7d0 __47-[SyphonServerDirectory handleAccounceRequest:]_block_invoke + 476
```

**Comment by bangnoise** [comment]
Hi - thanks for the report. I don't see either of these crashes following your steps, but I did hit a related one which I've just fixed.

There are still some unresolved issues in Simple Client which I'll look into - please try with my latest fix and let us know if you see these crashes in your own project.

I've updated the Simple Apps project, including adding an Xcode Workspace which makes it easier to build and debug both the Client and Server projects at the same time.

**Comment by smilingthax** [comment]
After (also) updating the Syphon-Simple repository I cannot reproduce the crash any more.

**Comment by smilingthax** [comment]
Hmm, ok, there also seems to be a problem with my custom builds:
It seems I previously did custom builds of Syphon-Simple without ARC (while Syphon-Framework does not use ARC, AFAICT), which did crash; when built with ARC (aka. -fobjc-arc) they don't.

**Comment by bangnoise** [comment]
You can't just toggle ARC on and off without also modifying the code - you have to add in all the retain/release calls if you disable it.

**Comment by smilingthax** [comment]
> You can't just toggle ARC on and off without also modifying the code - you have to add in all the retain/release calls if you disable it.

Yeah, I didn't do it on purpose... I did builds without xcode (I prefer to not have to install/update it on every machine I use...) and used the same settings for the Framework and the Client, without noticing that the settings for the Client differ from those used for the Framework in the xcode project.... Sorry for the trouble.

**Comment by bangnoise** [comment]
No problem!
