### ISSUE TITLE
Adobe Character Animator just took off Syphon!!! Please make all efforts to be on Character Animator again!

### ISSUE THREAD

**Issue by nunowonder** [Syphon/Syphon-Framework#80]
Hello, I'm very dissapointed with Adobe, specifically in Character Animator. They just took off something that really works well on OSX machines (I have a MacBookProM1Max64GB) and they simply say they took off that, and users shall use NDI instead, but NDI is slower, and takes more resources. Please help, your website tells that Ch is using Syphon. I really don't know a good reason why Adobe took of such a great tool, and I just hope you can do anything to make this an option in Adobe Ch.

**Comment by vade** [comment]
Had a conversation with some folks at Adobe about this via twitter.

Turns out this was removed due to deprecation of OpenGL, and them not knowing that Syphon supports a Metal back end. Part of that is on us for being slow to close the loop there.

Were going to continue communications with Adobe about the possibility of re-introducing Syphon.

Stay tuned.

**Comment by nunowonder** [comment]
Hi Vade! Thank you for your feedback, I feel better now, knowing that I'm not alone in this! I truly hope this EXCELLENT feature that Syphon + AppleM1 + Character Animator will work again, it's a no sense taking off such a perfect connection! There is a bug I found, but that's from Ch itself, with syphon, but I can work in a team of Syphon/ Adobe and me, because I really know what I found as that bug, and also I really work in a very intense way with Syphon + AppleM1 + Ch, LIVE, in OBS.

**Comment by vade** [comment]
Also, push come to shove, we can always release a Mercury Transmit Metal plugin for Character Creator if we need to!

**Comment by nunowonder** [comment]
What do you mean? It means I will be able to use it on OBS? Like Syphon? Without any delay?

**Comment by vade** [comment]
I mean a plugin for Adobe software which uses their Mercury Transmit engine. We have a private one which works for AE, Primere and other tools. It does rely on OpenGL, so it would need some love... but in theory thats a 'path' to supporting Character Animator (sorry, I keep saying Creator) without official Adobe sponsorship.

**Comment by nunowonder** [comment]
So... what do I need to do? I have to install that plugin? I'm sorry I'm just trying to understand the best solution, having the need of using NDI to communicate with Ch + OBS is such a shame, as this Apple thing called Syphon or Metal or whatever is so much better, almost resource-free and no delay...

**Comment by vade** [comment]
There is no solution today. 

I am *proposing* a path forward should Adobe continue to not natively support Syphon. Today, if you use the latest version, you are shit out of luck. Just to be clear :)

**Comment by vade** [comment]
For now, the ball is in Adobe's court and we'll see if we get any responses. As for the bug, thats Adobes bug in older Ch, so we can't do anything about it

**Comment by nunowonder** [comment]
I understand! Thank you so much, you gave me the feeling that this will be ok soon!

**Comment by nunowonder** [comment]
Thank you!Nuno MaravilhaNo dia 30/12/2022, às 18:23, Anton Marini ***@***.***> escreveu:﻿
Closed #80 as completed.
