### ISSUE TITLE
Frame Meta Data

### ISSUE THREAD

**Issue by maybites** [Syphon/Syphon-Framework#82]
Hi

This is not a feature request, rather an inquiry about its technical feasablilty:

Spout has the ability to pass on an arbitrary byte-buffer with each frame. ([link](https://github.com/leadedge/Spout2/blob/9db0efadba16e1d884164d348f556922cfc80c50/SPOUTSDK/SpoutGL/SpoutSender.h#L97) to header file). FYI: The latest MaxMSP - Spout package is already exposing it.

This is very interesting when sending realtime rendered images from game-engines together with camera intrinsic and extrinsic information to applications for spatial augemented reality.

Does such a functionality exist for syphon, too? And if not, with the current solution, could it be implemented into the framework in a similar way?

**Comment by bangnoise** [comment]
This is a dup of #29. This feature doesn't exist in Syphon at present.

As I understand it, in Spout this feature isn't tied to any particular frame so it's isn't particularly useful for per-frame data.

At present Syphon (and Spout) only present a single texture which is always the "latest" frame, but as Syphon currently works, synchronising changes in that texture with changes in other memory would introduce unwanted CPU/GPU dependencies. #29 remains open and we'll consider it if other changes in the framework make it possible.
