### ISSUE TITLE
hasNewFrame not working properly

### ISSUE THREAD

**Issue by Guido-assim** [Syphon/Syphon-Framework#90]
The [SyphonOpenGLClient hasNewFrame] call seems to not work properly, it returns true even when no new frame has been sent by the sender.
SyphonClientBase _lastFrameID is updated through SyphonOpenGLClient::newFrameImage -> SyphonClientBase::newSurface which seems to happen only once if the frame is not valid.
SyphonClientConnectionManager updates _frameID in SyphonClientConnectionManager::frameID when the IOSurface seed has changed.

**Comment by bangnoise** [comment]
Thanks for the report - this crept in with the refactor for Metal. Fixed now so subclasses update `_lastFrameID` for every frame.
