### ISSUE TITLE
SyphonServerDirectory sharedDirectory servers is always empty

### ISSUE THREAD

**Issue by Kautenja** [Syphon/Syphon-Framework#93]
I'm attempting to write a Syphon client in objective-C++, but can't seem to get the list of servers to populate. I've confirmed that there are in fact 2 Syphon servers running on my machine, and resolume Arena (which has its own Syphon client) seems to be able to find and render from said servers. The code I'm using to search for servers is provided below. Is there something I'm missing about how to find servers on the machine? It's worth noting that I am using code from the main branch.

```c++
    static std::vector<std::string> get_servers() {
        std::vector<std::string> names;
        NSArray *servers = [[SyphonServerDirectory sharedDirectory] servers];
        for (SyphonServer* server in servers) {
            NSString *name = [server name];
            names.push_back(std::string([name UTF8String]));
        }
        return names;
    }
```

**Comment by bangnoise** [comment]
The SyphonServerDirectory won't be populated immediately at app startup, if you're doing this at launch. Is that the case?

**Comment by Kautenja** [comment]
Indeed. I've tried polling in an infinite while loop too.

**Comment by vade** [comment]
Do you have a app kit runloop which iirc I required to let the Notification Center function?

**Comment by Kautenja** [comment]
That is likely the component that is missing. I'm running from a command line target that doesn't set up any event loop in the background as far as I am aware. It's essentially just a standard C++ `main` function that polls the server directory in a loop. What is the suggested approach for starting one of these event loops?

**Comment by bangnoise** [comment]
closing as dup of #75 

Here's a non-polling way to monitor for server announcements (there are other `SyphonServer*Notofication` for modification and removal too).

```objective-c++
int main(int argc, const char * argv[]) {
    [[NSNotificationCenter defaultCenter] addObserverForName:SyphonServerAnnounceNotification object:nil queue:nil usingBlock:^(NSNotification * _Nonnull note) {
        std::cout << "announce" << std::endl;
        NSDictionary *serverDescription = note.userInfo;
        // do something with serverDescription, eg instantiate a client
     }];
    bool quit = false;
    while (!quit) {
        // eg wake every second - you could just do
        // [[NSRunLoop currentRunLoop] run]
        // if you only need to respond to notifications. -run never returns.
        [[NSRunLoop currentRunLoop] runMode:NSDefaultRunLoopMode beforeDate:[NSDate dateWithTimeIntervalSinceNow:1.0]];
    }
    return 0;
}
```

**Comment by Kautenja** [comment]
This resolves my issue, thank you for your time and help.
