### ISSUE TITLE
Current state of Metal support

### ISSUE THREAD

**Issue by maybites** [Syphon/Syphon-Framework#95]
Hi

Sorry, this question would be better suited to a chat, but I couldn't find one..

Having finally figured out why Syphon didn't work properly with blender, a new challenge is here: With blender 4.0 only Metal is supported. This requires an update (or new wrapper all together) for the python wrapper I have been using: https://github.com/njazz/syphonpy - which only supports openGL. 

In the current Master there are indications of Metal support - how far is this development? 

I assume the plan is that openGL and Metal Apps can share textures, right?

regards

martin

**Comment by cansik** [comment]
For anyone interested in Metal, Syphon and Python: There is now [syphon-python](https://github.com/cansik/syphon-python), which is a Pyobjc based Python wrapper for the Syphon framework. It supports OpenGL as well as Metal based Syphon and has pre-built wheels that can be downloaded from [PyPi](https://pypi.org/project/syphon-python/).

**Comment by bangnoise** [comment]
@cansik great, if you want submit a PR to the [website repo](https://github.com/Syphon/syphon.github.io) to add it to the Applications section
