### ISSUE TITLE
Updated universal Syphon.framework for intel+arm64 ? 

### ISSUE THREAD

**Issue by benkuper** [Syphon/Syphon-Framework#97]
It seems that the current release Syphon SDK 5 is not usable when compiling for arm64, would it be possible to release an updated version ?

I'm mainly a windows dev and trying to integrate Syphon in my app ( https://benjamin.kuperberg.fr/Chataigne ), but I don't know much on mac and everytime I try again I don't even know where to start in order to generate the .framework from the xcode project. If there is some documentation on this I'm interested as well :)

Thank you

**Comment by bangnoise** [comment]
You can add the Syphon Xcode project to your own project, then link against the framework target and it will be built and integrated as needed.

**Comment by benkuper** [comment]
Thank you for your answer, this is not exactly a possibility as I'm using Juce and don't really want to have to integrate another project, I'd rather have everything precompiled.
I finally managed to get a compiled .framework by going to Product > Archive, and then deploying the archive. I honestly don't understand why XCode is such a pain but at least it works.

I'll close this now as many answers are available now :)
